default_install_hook_types:
  - pre-commit
  - pre-push

repos:
  - repo: local
    hooks:
      - id: ruff-check-fix
        name: ruff check --fix
        entry: python -m ruff check --fix
        language: system
        types_or:
          - python
          - pyi
        stages:
          - pre-commit

      - id: pytest-unit
        name: pytest unit tests
        entry: python -m pytest tests/unit
        language: system
        pass_filenames: false
        always_run: true
        stages:
          - pre-push
